### ISSUE TITLE
stm32l1xx-hal  fails to build

### ISSUE THREAD

**Issue by pdgilbert** [stm32-rs/stm32l1xx-hal#5]
stm32l1xx-hal is not building. I get (with and without feature rt):

~/stm32l1xx-hal$ cargo build --features stm32l100,stm32l151,rt
    Updating crates.io index
  Downloaded cast v0.2.3
   Compiling semver-parser v0.7.0
   Compiling typenum v1.11.2
  ...
   Compiling aligned v0.3.1
   Compiling cortex-m-rt-macros v0.1.6
error: symbol `DEVICE_PERIPHERALS` is already defined
      --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/stm32l1-0.5.0/src/stm32l162/mod.rs:155747:1
       |
155747 | static mut DEVICE_PERIPHERALS: bool = false;
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `stm32l1`.

To learn more, run the command again with --verbose.

**Comment by berkowski** [comment]
Just encountered this myself.  `stm32l1xx-hal` defines a few default traits that you may need to disable.  This is what I have in my `Cargo.toml` to get `stm32l1xx-hal` building for a STM32L151

```TOML
[dependencies.stm32l1xx-hal]
default-features = false
features = ["stm32l151", "rt"]
version = "^0.1"
```

**Comment by pdgilbert** [comment]
I think the Travic CI for this package (https://travis-ci.com/stm32-rs/stm32l1xx-hal) was broken by commit a228bac, which sets a default MCU. This default also means extra work for users that do not use the default MCU. The travis.yml could be fixed by the work-around proposed in the previous comment, but that seems like a lot of work compared to just not setting the default. Other HALs do not appear to set defaults. The commit did remove the rt default, which does seem to be consistent with other HALs. Removing defaults will make it easier for many users.

**Comment by howard0su** [comment]
I saw the fix is in 25 days ago. can we release a new version?

**Comment by pdgilbert** [comment]
I see the hal is building now, good to see some activity. I'll close this issue now (and probably open others after I work through some examples).
